name: aplikasi_absen_harian
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_glass_morphism: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.3
  glassmorphism: ^3.0.0
  google_fonts: ^6.3.3
  intl: ^0.20.2
  mobile_scanner: ^7.1.3
  supabase_flutter: ^2.10.3


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Untuk merubah Bg di homepage
  assets:
    - assets/images/bg_app.png
# Untuk merubah Bg di homepage
# Untuk merubah Bg di homepage
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  # Untuk merubah Bg di homepage
